### ISSUE TITLE
An error occurred while installing json, and Bundler cannot continue.

### ISSUE THREAD

**Issue by andruxnet** [getsentry/fastlane-plugin-sentry#10]
I can't make `fastlane add_plugin sentry` work, I keep getting errors.

I have spent all afternoon trying to fix this but I have to give up.. I'm not getting anywhere and can't find anything that helps me fix it.

First, the error mentioned json v1.8.6, I wasn't able to install it, but then I brew installed ruby, then rvm, then `rvm use` to make it use my newly installed ruby, and got it as far as making it not ask for v1.8.6 but v2.0.3 instead. It still says I need to first try to install json v2.0.3 before bundling, but even if I do run that install command and json v2.0.3 is installed successfully, the `fastlane add_plugin sentry` keeps erroring out. Am I'm missing something obvious here? Please help :(

This is the error I get when running the add_plugin action:

`
...
...
Using logging 2.1.0
Using rest-client 1.6.9
Using representable 2.3.0
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /Users/andrux/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/json-2.0.3/ext/json/ext/parser
/Users/andrux/.fastlane/bin/bundle/bin/ruby -r ./siteconf20170220-27513-1jqswzl.rb extconf.rb 
checking for rb_enc_raise() in ruby.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/Users/andrux/.fastlane/bin/bundle/bin/$(RUBY_BASE_NAME)
/Users/andrux/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file.
(RuntimeError)
...
...
An error occurred while installing json (2.0.3), and Bundler cannot continue.
Make sure that `gem install json -v '2.0.3'` succeeds before bundling.
`

Here's my gem_make.out log file:
`
current directory: /Users/andrux/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/json-2.0.3/ext/json/ext/parser
/Users/andrux/.fastlane/bin/bundle/bin/ruby -r ./siteconf20170220-27928-1e888pg.rb extconf.rb
checking for rb_enc_raise() in ruby.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
    --with-opt-dir
    --without-opt-dir
    --with-opt-include
    --without-opt-include=${opt-dir}/include
    --with-opt-lib
    --without-opt-lib=${opt-dir}/lib
    --with-make-prog
    --without-make-prog
    --srcdir=.
    --curdir
    --ruby=/Users/andrux/.fastlane/bin/bundle/bin/$(RUBY_BASE_NAME)
/Users/andrux/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
    from /Users/andrux/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:541:in `try_link0'
    from /Users/andrux/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:556:in `try_link'
    from /Users/andrux/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:735:in `try_func'
    from /Users/andrux/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:1020:in `block in have_func'
    from /Users/andrux/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:911:in `block in checking_for'
    from /Users/andrux/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:351:in `block (2 levels) in postpone'
    from /Users/andrux/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:321:in `open'
    from /Users/andrux/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:351:in `block in postpone'
    from /Users/andrux/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:321:in `open'
    from /Users/andrux/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:347:in `postpone'
    from /Users/andrux/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:910:in `checking_for'
    from /Users/andrux/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:1019:in `have_func'
    from extconf.rb:4:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Users/andrux/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/extensions/x86_64-darwin-15/2.2.0-static/json-2.0.3/mkmf.log

extconf failed, exit code 1

`

And here's my mkmf.log file
`
"/usr/bin/clang -o conftest -I/Users/andrux/.fastlane/bin/bundle/include/ruby-2.2.0/x86_64-darwin15 -I/Users/andrux/.fastlane/bin/bundle/include/ruby-2.2.0/ruby/backward -I/Users/andrux/.fastlane/bin/bundle/include/ruby-2.2.0 -I. -I/Users/crashlytics/buildAgent/work/2484be8b71880c21/bundle-2.13.0/fastlane_lib/dependencies/include -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT   -mmacosx-version-min=10.10 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -pipe conftest.c  -L. -L/Users/andrux/.fastlane/bin/bundle/lib -L. -L/Users/crashlytics/buildAgent/work/2484be8b71880c21/bundle-2.13.0/fastlane_lib/dependencies/lib -fstack-protector     -lruby-static -framework CoreFoundation  -lpthread -ldl -lobjc "
ld: warning: directory not found for option '-L/Users/crashlytics/buildAgent/work/2484be8b71880c21/bundle-2.13.0/fastlane_lib/dependencies/lib'
ld: library not found for -lruby-static
clang: error: linker command failed with exit code 1 (use -v to see invocation)
checked program was:
/* begin */
1: #include "ruby.h"
2:
3: int main(int argc, char **argv)
4: {
5:   return 0;
6: }
/* end */
`

**Comment by andruxnet** [comment]
Here's the complete output of what I have been trying:

https://gist.github.com/andruxnet/0d4ee2993153c4a704d8bfec08764e02

**Comment by andruxnet** [comment]
Well, apparently copying and pasting all logs and giving up on this actually fixed it! I'll just leave it like that and don't do anything stupid to prevent it from breaking.

thanks
