### ISSUE TITLE
error: http error: generic error (404)

### ISSUE THREAD

**Issue by n1mda** [getsentry/fastlane-plugin-sentry#11]
I get an error when I try to upload the dSYM to Sentry.
Manually running the command
```
sentry-cli upload-dsym --org company --project my-app myapp.app.dSYM.zip
```
works, but running fastlane with these settings fail

Fastfile:
```
desc "Upload dSYM to Sentry"
  lane :dsym do
    sentry_upload_dsym(
      auth_token: ENV['SENTRY_AUTH_TOKEN'],
      org_slug: 'company',
      project_slug: 'my-app',
      dsym_path: './myapp.app.dSYM.zip'
    )
  end
```

```
$ fastlane dsym --verbose
Successfully loaded Appfile at path '/Users/john/code/my-app/fastlane/Appfile'
- app_identifier: 'com.my.app'
- apple_id: 'account@company.com'
- team_id: '[[DEV_PORTAL_TEAM_ID]]'
-------
DEBUG [2017-03-01 22:33:48.06]: Checking if there are any plugins that should be loaded...
DEBUG [2017-03-01 22:33:48.19]: Loading 'fastlane-plugin-aws_s3' plugin
INFO [2017-03-01 22:33:48.29]: gem 'fastlane-plugin-aws_s3' is already installed
DEBUG [2017-03-01 22:33:48.34]: Loading 'fastlane-plugin-sentry' plugin
INFO [2017-03-01 22:33:48.45]: gem 'fastlane-plugin-sentry' is already installed
+------------------------+---------+--------------------+
|                     Used plugins                      |
+------------------------+---------+--------------------+
| Plugin                 | Version | Action             |
+------------------------+---------+--------------------+
| fastlane-plugin-aws_s3 | 0.2.1   | aws_s3             |
| fastlane-plugin-sentry | 1.0.0   | sentry_upload_dsym |
+------------------------+---------+--------------------+

INFO [2017-03-01 22:33:48.56]: -------------------------------------------------
INFO [2017-03-01 22:33:48.56]: --- Step: Verifying required fastlane version ---
INFO [2017-03-01 22:33:48.56]: -------------------------------------------------
INFO [2017-03-01 22:33:48.56]: Your fastlane version 2.17.1 matches the minimum requirement of 2.17.1  ✅
INFO [2017-03-01 22:33:48.57]: ------------------------------
INFO [2017-03-01 22:33:48.57]: --- Step: default_platform ---
INFO [2017-03-01 22:33:48.57]: ------------------------------
INFO [2017-03-01 22:33:48.58]: Driving the lane 'ios dsym' 🚀
INFO [2017-03-01 22:33:48.60]: --------------------------------
INFO [2017-03-01 22:33:48.60]: --- Step: sentry_upload_dsym ---
INFO [2017-03-01 22:33:48.60]: --------------------------------
INFO [2017-03-01 22:33:48.64]: sentry-cli 0.25.0 installed!
INFO [2017-03-01 22:33:48.65]: Starting sentry-cli...
INFO [2017-03-01 22:33:49.88]: Uploading symbols
INFO [2017-03-01 22:33:49.88]: Finding symbols in /Users/john/code/my-app/myapp.app.dSYM.zip...
INFO [2017-03-01 22:33:49.88]: Creating DSym batch
INFO [2017-03-01 22:33:49.88]: /Users/john/code/my-app/myapp.app.dSYM.zip (zip archive)
INFO [2017-03-01 22:33:49.88]: DebugSymbols/AFAmazonS3Manager.framework.dSYM/Contents/Resources/DWARF/AFAmazonS3Manager
INFO [2017-03-01 22:33:49.88]: DebugSymbols/AFNetworking.framework.dSYM/Contents/Resources/DWARF/AFNetworking
INFO [2017-03-01 22:33:49.88]: DebugSymbols/Alamofire.framework.dSYM/Contents/Resources/DWARF/Alamofire
INFO [2017-03-01 22:33:49.88]: DebugSymbols/Bohr.framework.dSYM/Contents/Resources/DWARF/Bohr
INFO [2017-03-01 22:33:49.88]: DebugSymbols/Cosmos.framework.dSYM/Contents/Resources/DWARF/Cosmos
INFO [2017-03-01 22:33:49.88]: DebugSymbols/DGActivityIndicatorView.framework.dSYM/Contents/Resources/DWARF/DGActivityIndicatorView
INFO [2017-03-01 22:33:49.88]: DebugSymbols/DPLocalization.framework.dSYM/Contents/Resources/DWARF/DPLocalization
INFO [2017-03-01 22:33:49.88]: DebugSymbols/FontAwesome_swift.framework.dSYM/Contents/Resources/DWARF/FontAwesome_swift
INFO [2017-03-01 22:33:49.88]: DebugSymbols/FormatterKit.framework.dSYM/Contents/Resources/DWARF/FormatterKit
INFO [2017-03-01 22:33:49.88]: DebugSymbols/GoogleMaterialIconFont.framework.dSYM/Contents/Resources/DWARF/GoogleMaterialIconFont
INFO [2017-03-01 22:33:49.88]: DebugSymbols/HexColors.framework.dSYM/Contents/Resources/DWARF/HexColors
INFO [2017-03-01 22:33:49.88]: DebugSymbols/ImagePicker.framework.dSYM/Contents/Resources/DWARF/ImagePicker
INFO [2017-03-01 22:33:49.88]: DebugSymbols/KSCrash.framework.dSYM/Contents/Resources/DWARF/KSCrash
INFO [2017-03-01 22:33:49.88]: DebugSymbols/Mantle.framework.dSYM/Contents/Resources/DWARF/Mantle
INFO [2017-03-01 22:33:49.88]: DebugSymbols/OpenInGoogleMaps.framework.dSYM/Contents/Resources/DWARF/OpenInGoogleMaps
INFO [2017-03-01 22:33:49.88]: DebugSymbols/PPSSignatureView.framework.dSYM/Contents/Resources/DWARF/PPSSignatureView
INFO [2017-03-01 22:33:49.88]: Detecting dsyms to upload
ERROR [2017-03-01 22:33:49.88]: error: http error: generic error (404)
WARN [2017-03-01 22:33:49.89]: Lane Context:
INFO [2017-03-01 22:33:49.89]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios dsym"}
ERROR [2017-03-01 22:33:49.89]: Error while trying to upload dSYM to Sentry
INFO [2017-03-01 22:33:49.89]: Successfully generated documentation at path '/Users/john/code/my-app/fastlane/README.md'

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 💥   | sentry_upload_dsym                  | 1           |
+------+-------------------------------------+-------------+

+--------+--------------+----------------+
|        Plugin updates available        |
+--------+--------------+----------------+
| Plugin | Your Version | Latest Version |
+--------+--------------+----------------+
| aws_s3 | 0.2.1        | 0.2.2          |
+--------+--------------+----------------+
INFO [2017-03-01 22:33:49.92]: To update all plugins, just run
INFO [2017-03-01 22:33:49.92]: $ fastlane update_plugins

ERROR [2017-03-01 22:33:49.92]: fastlane finished with errors

#######################################################################
# fastlane 2.19.1 is available. You are on 2.17.1.
# It is recommended to use the latest version.
# Please update using `fastlane update_fastlane`.
#######################################################################

2.19.1 Hot fix for provisioning profile creation/deletion
* Re-implement csrf token retreval for provisioning profiles (#8410)
* dont attempt to create apps on the dev center and itc if mac app (#8404)

2.19.0 Improvements
* Expand the binary path in `upload_symbols_to_crashlytics` action (#8353)
* Add `keychain_path` option to `delete_keychain` action (#8003)
* [cert] Print a better error message when user is not Team Admin (#8397)
* [match] Fix bug with foreign branch shallow clone (#8341)
* [match] Set Provisioning Profile path for environment variables (#8280)
* [scan] Expose custom report file name as SCAN_CUSTOM_REPORT_FILE_NAME (#8351)
* [spaceship] Refactor fetch_details access the details directly (#8363)
* [spaceship Introduce SPACESHIP_AVOID_XCODE_API env variable and revert to using Xcode API for provisioning profiles as the default behavior so that performance is better and xcode managed profiles are available. (#8359)

2.18.3 Fix update checker
* Fix fastlane update checking for sub-tools (#8343)

To see all new releases, open https://github.com/fastlane/fastlane/releases

Please update using `fastlane update_fastlane`
/Users/john/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.17.1/fastlane_core/lib/fastlane_core/ui/interface.rb:146:in `user_error!': [!] Error while trying to upload dSYM to Sentry (FastlaneCore::Interface::FastlaneError)
	from /Users/john/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.17.1/fastlane_core/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /Users/john/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-plugin-sentry-1.0.0/lib/fastlane/plugin/sentry/actions/sentry_upload_dsym.rb:99:in `handle_error'
	from /Users/john/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-plugin-sentry-1.0.0/lib/fastlane/plugin/sentry/actions/sentry_upload_dsym.rb:82:in `block in call_sentry_cli'
	from /Users/john/.fastlane/bin/bundle/lib/ruby/2.2.0/open3.rb:199:in `popen_run'
	from /Users/john/.fastlane/bin/bundle/lib/ruby/2.2.0/open3.rb:93:in `popen3'
	from /Users/john/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-plugin-sentry-1.0.0/lib/fastlane/plugin/sentry/actions/sentry_upload_dsym.rb:73:in `call_sentry_cli'
	from /Users/john/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-plugin-sentry-1.0.0/lib/fastlane/plugin/sentry/actions/sentry_upload_dsym.rb:43:in `run'
	from /Users/john/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.17.1/fastlane/lib/fastlane/runner.rb:243:in `block (2 levels) in execute_action'
	from /Users/john/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.17.1/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/john/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.17.1/fastlane/lib/fastlane/runner.rb:221:in `block in execute_action'
	from /Users/john/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.17.1/fastlane/lib/fastlane/runner.rb:217:in `chdir'
	from /Users/john/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.17.1/fastlane/lib/fastlane/runner.rb:217:in `execute_action'
	from /Users/john/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.17.1/fastlane/lib/fastlane/runner.rb:139:in `trigger_action_by_name'
	from /Users/john/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.17.1/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
	from Fastfile:57:in `block (2 levels) in parsing_binding'
	from /Users/john/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.17.1/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/john/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.17.1/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/john/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.17.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/john/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.17.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/john/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.17.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/john/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.17.1/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
	from /Users/john/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.17.1/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Users/john/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.17.1/fastlane/lib/fastlane/commands_generator.rb:105:in `block (2 levels) in run'
	from /Users/john/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
	from /Users/john/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
	from /Users/john/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-4.4.3/lib/commander/command.rb:153:in `run'
	from /Users/john/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-4.4.3/lib/commander/runner.rb:446:in `run_active_command'
	from /Users/john/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.17.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /Users/john/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!'
	from /Users/john/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.17.1/fastlane/lib/fastlane/commands_generator.rb:302:in `run'
	from /Users/john/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.17.1/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Users/john/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.17.1/fastlane/lib/fastlane/cli_tools_distributor.rb:63:in `take_off'
	from /Users/john/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.17.1/bin/fastlane:15:in `<top (required)>'
	from /Users/john/.fastlane/bin/bundle/bin/fastlane:22:in `load'
	from /Users/john/.fastlane/bin/bundle/bin/fastlane:22:in `<main>'
```

**Comment by HazAT** [comment]
Can you check your project/organization slug again please ... 
Copy it directly from the url of sentry ...
<img width="415" alt="daniel_griesser___mathtastical" src="https://cloud.githubusercontent.com/assets/363802/23499203/7aeefa88-ff2b-11e6-9213-1506d3ac8fb5.png">

**Comment by n1mda** [comment]
The slugs are correct, have double checked

**Comment by HazAT** [comment]
Can you please run fastlane with `--verbose` and send me the output to daniel@sentry.io ?

**Comment by n1mda** [comment]
The output above is with `--verbose`. I sent an email to daniel :)

**Comment by HazAT** [comment]
Hey ... sry haven't seen that ...
Can you please upgrade the plugin to version `1.0.1`, I added additonal verbose log output.
Please send the uncensored version of the fastfile and output to my email again please.

**Comment by JagCesar** [comment]
I'm having the same issue. Sending verbose output to the e-mail mentioned above.

**Comment by HazAT** [comment]
Guys ... please upgrade to `1.0.2` the bug has been fixed.
The default parameter was pointing to an old sentry endpoint and the returned error wasn't that helpful.
It works now, promised 💯 😅

**Comment by JagCesar** [comment]
![giphy-4](https://cloud.githubusercontent.com/assets/923548/23513328/e81dd18c-ff63-11e6-9f28-040d4a93d8d7.gif)

**Comment by n1mda** [comment]
![](http://www.reactiongifs.com/wp-content/uploads/2013/10/I-love-you-gif-Tim-Gunn.gif)

Thank you.

Btw @JagCesar come work for us, you can reach me at axel.moller@budbee.com ;)
